# Generated by Django 2.2 on 2019-06-11 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('steez', models.CharField(choices=[('S', 'Street'), ('P', 'Park'), ('C', 'Cruise')], default='S', max_length=1)),
                ('trick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Trick')),
            ],
        ),
    ]
